language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
branches:
  only:
  - master
install:
  - npm install
  - npm install -g gulp-cli
script:
  - gulp templates
  - echo "Skipping tests"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  local-dir: project
  on:
    branch: master
